name: CI
on: [pull_request]

jobs:
  static-unit:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Prepare PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: sockets
      - name: Composer Update
        run: composer update
      - name: Static and Unit tests
        run: |
          ./vendor/bin/phpstan analyse -c ./tests/static/phpstan.neon
          ./vendor/bin/phpcs --encoding=utf-8 --standard=PSR2 --extensions=php src/*

